### ISSUE TITLE
get only returns true or false?

### ISSUE THREAD

**Issue by marijnvandevoorde** [alekseykorzun/memcached-wrapper-php#10]
Or am I overlooking something? Get method doesn't really make a lot of sense, unless I'm truly overlooking something here?

**Comment by AlekseyKorzun** [comment]
@mrnnn What method? Can you please clarify.

**Comment by mrnnn** [comment]
Hey Aleksey. Overlooked the & before resource. So you use a reference param to store the results :+1: 
Just found it confusing that it doesn't work the same way as memcached::get, that's all.

Anyway, don't really have use for this atm, but used the graceful cache expiry idea to write a cache wrapper for the cakephp framwork, so thanks ;-)

**Comment by AlekseyKorzun** [comment]
Awesome :+1: 

Going to close this out, ping me if you need anything!
